# make a python program of 8 key functions in non repeating manner (set)

s = set()
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)
n = int(input("Enter number: "))
s.add(n)

print(s)